config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/inadimplente'
  root 'welcome#index'
  get 'admin', to: 'admin#index'
  get 'dadosuser', to: 'admin#dadosuser'
  get '/manager_users', to: 'manager_users#index', as: 'manager_users_index'
  get 'inadimplente', to: 'static_pages#inadimplente'
  resources :employees
  devise_for :users
  resources :keylockers 

  resources :employees do
    member do
      patch 'toggle_and_save_status'
      put 'reset_pin'
    end
  end

  resources :keylockers do
    member do
      patch 'toggle_and_save_status'
    end
  end

  patch 'manager_users/:id/toggle_finance', to: 'manager_users#toggle_finance', as: :toggle_finance
  patch 'manager_users/:id/toggle_role', to: 'manager_users#toggle_role', as: :toggle_role

  resources :manager_users do
    member do
      delete :destroy
    end
  end

  get '/history_entries', to: 'history_entries#index'

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]

  resources :history_entries, only: [:index, :show, :new, :create, :destroy]


  # config/routes.rb
  resources :user_lockers do
    member do
      post 'assign_keylocker'
      delete 'remove_keylocker/:keylocker_id', to: 'user_lockers#remove_keylocker', as: 'remove_keylocker'
    end
  end

  

  #resources :keylockers, defaults: { format: 'json' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do
    namespace :v1 do
      resources :employees
      get '/employees', to: 'employees#index'
      get '/employees/:employee_id/belongs_to_keylocker/:keylocker_id', to: 'employees#belongs_to_keylocker'
      post '/esp8288params', to: 'employees#esp8288params', via: :post
      post 'check_user', to: 'employees#check_user'
      post 'count_and_track_spaces', to: 'employees#count_and_track_spaces'
      post 'return_key', to: 'employees#return_key'
      post 'key_locker_history', to: 'employees#key_locker_history'
      get '/outro_metodo', to: 'employees#outro_metodo'
      resources :keylockers  # Ajuste para o novo nome do controlador
      #post '/auth/sign_in', to: 'authentication#sign_in'
      devise_for :users, skip: [:registrations], controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
    before_create :set_default_status
    has_many :workdays, dependent: :destroy
    belongs_to :user
    has_and_belongs_to_many :keylockers
    has_one_attached :profile_picture
  
    accepts_nested_attributes_for :workdays, reject_if: :all_blank, allow_destroy: true
    validate :at_least_one_keylocker

  
    private

    def at_least_one_keylocker
      errors.add(:base, 'Deve haver pelo menos um locker atribuído') if keylockers.none?
    end
  
    def set_default_status
      self.status ||= 'debloqueado'
    end
  end
  

app/controllers/api/v1/employees_controller.rb
I18n.locale = :pt

module Api
  module V1
    class EmployeesController < ApplicationController
      skip_before_action :verify_authenticity_token, only: [:esp8288params, :check_user, :count_and_track_spaces, :outro_metodo, :key_locker_history]
      skip_before_action :authenticate_user!, only: [:esp8288params, :check_user, :count_and_track_spaces, :outro_metodo, :key_locker_history]
      before_action :initialize_positions_text

      def index
        @employees = Employee.all
        render json: @employees
      end

      def esp8288params
        id_nv_usr = params[:ID_NV_USR]
        rfid_nv_usr = params[:RFID_NV_USR]
        snh_nv_usr = params[:SNH_NV_USR]
    
        # Encontre o funcionário com base no campo PIN
        employee = Employee.find_by(PIN: id_nv_usr)
    
        if employee
          # Atualize o campo cardRFID se RFID_NV_USR estiver presente
          employee.update(cardRFID: rfid_nv_usr) if rfid_nv_usr.present?
    
          # Atualize os campos pswdSmartlocker se SNH_NV_USR estiver presente
          if snh_nv_usr.present?
            employee.update(pswdSmartlocker: snh_nv_usr)
            render json: { message: 'Usuário cadastrado com sucesso' }
          else
            render json: { message: 'SNH_NV_USR é obrigatório' }, status: :unprocessable_entity
          end
        else
          render json: { message: 'ID_NV_USR não corresponde a nenhum PIN de funcionário' }, status: :unprocessable_entity
        end
      end

      def check_user
        employee_info = nil
        snh_keypad_usr = params[:SNH_KEYPAD_USR]
        card_rfid = params[:CARD_RFID]
      
        if snh_keypad_usr.present?
          employee = Employee.find_by(pswdSmartlocker: snh_keypad_usr)
        elsif card_rfid.present?
          employee = Employee.find_by(cardRFID: card_rfid)
        else
          # Nenhum método de autenticação fornecido ou nenhum funcionário encontrado
          render json: { message: 'Método de autenticação não fornecido ou funcionário não encontrado.' }
          return  # Adiciona um retorno para sair da ação
        end
        

        workdays = employee.workdays

        current_day = I18n.l(Time.now, format: '%A').capitalize
        puts "Current day: #{current_day.inspect}"

        today_workday = workdays.find { |wd| wd.dayofweek&.include?(current_day) }
        puts "Today Workday: #{today_workday.inspect}"

        if today_workday.present? && today_workday.dayofweek.present?
          today_workday_start = Time.parse(today_workday&.start.strftime('%H:%M:%S')) # Formata o início para o formato correto
          today_workday_end = Time.parse(today_workday&.end.strftime('%H:%M:%S'))     # Formata o fim para o formato correto

          puts "Today Workday Start: #{today_workday_start.inspect}"
          puts "Today Workday End: #{today_workday_end.inspect}"

          current_time = Time.now
          puts "Current Time: #{current_time}"

          if current_time.between?(today_workday_start, today_workday_end)
            @employee_info = {
              name: employee.name,
              lastname: employee.lastname,
              user_status: employee.status,
              datetime: Time.now.strftime('%Y-%m-%d %H:%M:%S'),
              keylockers: employee.keylockers.map do |keylocker|
                {
                  keylocker_owner: keylocker.owner,
                  keylocker_name: keylocker.nameDevice,
                  keylocker_status: keylocker.status
                }
              end
            }
            session[:employee_info] = @employee_info
            render json: @employee_info
          else
            render json: { message: 'Funcionário fora do horário de serviço.' }
          end
        else
          render json: { message: 'Não é o dia de trabalho desse funcionário' }
        end
      end

      def count_and_track_spaces
        @employee_info = session[:employee_info] 
        binary_sequence = params[:binary_sequence]
        @binary_sequence = params[:binary_sequence]

        if binary_sequence.present?
          result = {}
          positions = binary_sequence.chars.each_with_index.select { |value, index| value == '0' }.map { |_, index| index + 1 }
          register_positions(positions)
          positions_keys = positions.map { |position| "chave #{position}" }.join(' e ')

          #session[:binary_sequence_before] = @binary_sequence #zera o session
          puts "Sequencia salva na Session: #{session[:binary_sequence_before]}"
          vetor_anterior = session[:binary_sequence_before].chars.map(&:to_i)
          puts "Sequencia Recebida #{@binary_sequence}"
          vetor_atual = @binary_sequence.chars.map(&:to_i)

          alteracoes = vetor_atual.each_with_index.select do |value, index|
            puts "Iteration: index=#{index + 1}, salvoSessao=#{vetor_anterior[index]}, valorAtual=#{value}"
            value != vetor_anterior[index]
          end

          alteracoes.each do |value, index|
            puts "Elemento na posição #{index} mudou de #{vetor_anterior[index]} para #{vetor_atual[index]}"
          end

          posicoes_alteradas = alteracoes.map { |value, index| index + 1 }
          puts "Posições alteradas: #{posicoes_alteradas}"


          render json: {
          employee_info: @employee_info,
          chaves_ocupadas: positions_keys,
          chaves_devolvidas: posicoes_alteradas
        }

        log_data = {
          employee_info: @employee_info,
        }
      
          # Adicionar informações ao log apenas se a sequência binária estiver presente
          Log.create(log_data) if binary_sequence.present?
        else
          render json: { message: 'Sequência binária não fornecida' }, status: :unprocessable_entity
        end
      end

      def key_locker_history
        @employee_info = session[:employee_info] 
        owner = params[:owner]
        name_device = params[:nameDevice]
        binary_sequence = params[:binarySequence]


        lockerOwner = Keylocker.find_by(owner: owner)
        puts "lockerOwner: #{lockerOwner.inspect}"

        lockerDevice = Keylocker.find_by(nameDevice: name_device)
        puts "lockerDevice: #{lockerDevice.inspect}"
      
        if lockerOwner.present? && lockerDevice.present? 
          keys_in_place = []
          keys_out_of_place = []
          last_changed_position = nil

          binary_sequence.chars.each_with_index do |value, index|
            if value == '1'
              keys_in_place << index + 1 # Adiciona 1 para começar a contar da posição 1
            elsif value == '0'
              keys_out_of_place << index + 1
            end
          end

          keys_in_place_text = "Chaves livres: #{keys_in_place.join(', ')}"
          keys_out_of_place_text = "Chaves ocupadas: #{keys_out_of_place.join(', ')}"
          
          render json: {
            proprietario: owner,
            device: name_device,
            informação: @employee_info,
            todas_chaves: binary_sequence,
            chaves_livres: keys_in_place_text,
            chaves_ocupadas: keys_out_of_place_text,
            created_at: Time.now
          }

          puts "Chaves Vetor: #{binary_sequence.inspect}"

          history_entry = {
            owner: owner,
            name_device: name_device,
            employee_info: @employee_info,
            keys_taken: keys_in_place_text,
            keys_returned: keys_out_of_place_text,
            sequence_order: binary_sequence.chars.map(&:to_i),
            created_at: Time.now
          }
          puts "history_entry: #{history_entry.inspect}"
          HistoryEntry.create(history_entry)if binary_sequence.present?
          puts "historico criado e salvo"
        else
          render json: { error: 'Proprietário ou nome do dispositivo inválido' }, status: :unprocessable_entity
        end
      end

      def outro_metodo
        @employee_info = session[:employee_info]  # Recupera de sessão
        # Agora você pode acessar @employee_info aqui
        puts "Employee Info em outro_metodo: #{@employee_info.inspect}" if @employee_info.present?
        render json: @employee_info.to_json if @employee_info.present?
      end

      def update
        respond_to do |format|
          if @employee.update(employee_params)
            format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
            format.json { render :show, status: :ok, location: @employee }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @employee.errors, status: :unprocessable_entity }
          end
        end
      end

      def belongs_to_keylocker
        @employee = Employee.find(params[:employee_id])
        @keylocker = Keylocker.find(params[:keylocker_id])
    
        authorize @employee # Certifique-se de adicionar isso se estiver usando Pundit ou outra gem de autorização
    
        belongs_to_keylocker = @employee.keylockers.include?(@keylocker)
    
        render json: { belongs_to_keylocker: belongs_to_keylocker }
      end

      private

      def set_employee
        @employee = Employee.find(params[:id])
      end

      def initialize_key_status
        @key_status = Hash.new { |hash, key| hash[key] = { status: :available, returned: false } }
      end

      def parse_returned_keys(returned_keys_param)
        return [] unless returned_keys_param.present?
        returned_keys_param.split(',').map(&:to_i)
      end

      def initialize_positions_text
        @positions_text = Hash.new(0)
        session[:counter] ||= {}
      end

      def increment_positions_text
        @positions_text.transform_values! { |value| value + 1 }

        # Garante que session[:counter] seja sempre um hash
        session[:counter] ||= {}
        session[:counter] = (session[:counter].is_a?(Hash) ? session[:counter] : {}).transform_values! { |value| value.to_i + 1 }
      end

app/helpers/api/v1/employees_helper.rb
module Api::V1::EmployeesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-8 mb-4">
      <div class="card mb-4">
        <div class="card-header py-3">
          <h5 class="mb-0">Cadastrar novo colaborador</h5>
        </div>
        <div class="card-body">
          <form>
            <!-- 2 column grid layout with text inputs for the first and last names -->
            <div class="row mb-4">
              <div class="col">
                <div class="form-outline">
                  <%= form.label :Nome, class: "form-label" %>
                  <%= form.text_field :name, id: 'form7Example1', class: 'form-control' %>
                </div>
              </div>
              <div class="col">
                <div class="form-outline">
                  <%= form.label :Sobrenome, class: "form-label" %>
                  <%= form.text_field :lastname, id: 'form7Example1', class: 'form-control' %>
                </div>
              </div>
            </div>

            <!-- Text input -->
            <div class="form-outline mb-4">
              <%= form.label :Nome_da_Empresa, class: "form-label" %>
              <%= form.text_field :companyID, id: 'form7Example3', class: 'form-control' %>
            </div>

            <div class="row mb-4">

              <div class="col">
                <div class="form-outline">
                  <%= form.label :Telefone, class: "form-label" %>
                  <%= form.text_field :phone, id: 'phoneNumberInput', class: 'form-control', oninput: "handleInputChange()" %>
                </div>
              </div>

              <div class="col">
                <div class="form-outline">
                  <%= form.label :Cargo, class: "form-label" %>
                  <%= form.text_field :function, id: 'form7Example1', class: 'form-control' %>
                </div>
              </div>
            </div>

            <%= form.fields_for :workdays do |workday_fields| %>
              <div class="field">
                <%= workday_fields.label :Dias_de_Trabalho %>
                </br>
                <% ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'].each do |day| %>
                  <%= check_box_tag 'employee[workdays_attributes][0][dayofweek][]', day, workday_fields.object.dayofweek.include?(day) %>
                  <%= label_tag "employee[workdays_attributes][0][dayofweek][]_#{day}", day %><br>
                <% end %>
              </div>

              <div class="row mb-4">
                <div class="col">
                  <div class="form-outline">
                    <%= workday_fields.label :Hora_de_Inicio, class: "form-label" %>
                  <%= workday_fields.time_field :start, id: 'form7Example1', class: 'form-control' %>
                </div>
              </div>

              <div class="col">
                <div class="form-outline">
                  <%= workday_fields.label :Hora_de_Encerramento, class: "form-label" %>
                  <%= workday_fields.time_field :end, id: 'form7Example1', class: 'form-control', data: { 'timepicker' => true }  %>
                </div>
              </div>

              <div class="col">
                <div class="form-outline">
                  <%= workday_fields.label :Expediente_no_Feriado, class: "form-label" %>
                  </br>
                  <%= workday_fields.check_box :holiday,  class: 'form-check-input' %>
                </div>
              </div>
            </div>
            <% end %>

            <!-- Text input -->
            <div class="form-outline mb-4">
              <%= form.label :Foto_do_Colaborador, class: "form-label" %>
              <%= form.file_field :profile_picture, id: 'form7Example3', class: 'form-control' %>
            </div>

            <div class="d-flex">
              <div class="form-group mr-2">
                <%= form.submit 'Cadastrar Colaborador', class: 'btn btn-primary' %>
              </div>

              <div class="form-group">
                <%= link_to "Voltar", employees_path, class: 'btn btn-success' %>
              </div>            
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
<% end %>


<script>
document.addEventListener('turbolinks:load', function() {
  var input = document.querySelector("#user_phone"); // Certifique-se de substituir "user_phone" pelo ID real do seu campo de telefone
  var iti = window.intlTelInput(input, {
    separateDialCode: true,
    utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/utils.js",
  });

  // Atualize a bandeira ao carregar a página, se necessário
  var countryCode = iti.getSelectedCountryData().iso2;
  document.querySelector("#phone-flag").innerHTML = `<img src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/flags/1x1/${countryCode}.svg" alt="${countryCode.toUpperCase()}">`;

  // Atualize a bandeira quando o país for alterado
  input.addEventListener('countrychange', function() {
    var countryCode = iti.getSelectedCountryData().iso2;
    document.querySelector("#phone-flag").innerHTML = `<img src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/flags/1x1/${countryCode}.svg" alt="${countryCode.toUpperCase()}">`;
  });
});
</script>

<script>
function formatPhoneNumber(phone) {
  const phoneDigits = phone.replace(/\D/g, '');
  const formattedPhone = `${phoneDigits.slice(0, 2)}-${phoneDigits.slice(2, 11)}`;
  return formattedPhone;
}

function handleInputChange() {
  const inputElement = document.getElementById('phoneNumberInput');
  const formattedPhoneNumber = formatPhoneNumber(inputElement.value);
  console.log(formattedPhoneNumber);
}
</script>

app/views/employees/edit.html.erb
<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Meus Colaboradores</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<p style="color: green"><%= notice %></p>

<% if current_user.admin? %>
                       
    <% else %>
    <%= link_to new_employee_path, class: "btn btn-primary mt-3" do %>
        <i class="fa fa-plus"></i> Cadastrar Novo Colaborador
    <% end %>                 
<% end %>

<% if @employees.present? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 col-lg-9"> 
        <div class="right_col mt-3" role="main">
          <div class="row">
            <% @employees.each do |employee| %>
                <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="card mb-4">
                </br>
                    <div class="text-center">
                        <p>
                            <% if employee.profile_picture.attached? %>
                            <%= image_tag employee.profile_picture, size: '288x288' %>
                            <% else %>
                            <%= image_tag "user.png", size: '288x288' %>
                            <% end %>
                        </p>
                    </div>
                <div class="card-body">
                  <p>
                    <strong>Nome:</strong>
                    <%= employee.name %> <%= employee.lastname %>
                  </p>

                  <p>
                    <strong>Empresa:</strong>
                    <%= employee.companyID %>
                  </p>

                  <p>
                  <strong>PIN:</strong>
                  <%= employee.PIN %>
                </p>

                  <p>
                    <strong>Telefone:</strong>
                    <%= employee.phone %>
                  </p>

                  <p>
                    <strong>Cargo:</strong>
                    <%= employee.function %>
                  </p>

                  <% if current_user.admin? %>
                    <p>
                        <strong>Meus Lockers:</strong>
                        <% if employee.keylockers.any? %>
                            <ul>
                            <% employee.keylockers.each do |keylocker| %>
                                <li>
                                <%= keylocker.nameDevice %> - <%= keylocker.status %>
                                </li>
                            <% end %>
                            </ul>
                        <% else %>
                            Nenhum locker associado a esse funcionário.
                        <% end %>
                    </p>
                    <% else %>
                                   
                  <% end %>
                 
                  <div class="text-center mt-3">
                    <%= link_to employee, class: "btn btn-warning d-inline-block mr-2" do %>
                      <i class="fa fa-search"></i> Exibir
                    <% end %>
                
                    <%= link_to edit_employee_path(employee), class: "btn btn-success d-inline-block mr-2" do %>
                        <i class="fa fa-edit"></i> Editar
                    <% end %>
                
                    <%= button_to employee, method: :delete, class: 'btn btn-danger d-inline-block mt-3', title: 'Excluir', id: "delete-btn-#{employee.id}" do %>
                        <i class="fa fa-trash"></i> Excluir
                    <% end %>   
                  </div>
                  </br>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div style="text-align: center;">
    <p>Não existe nenhum funcionário</p>
  </div>
<% end %>
            
<div class="text-center mt-3 d-flex justify-content-center">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <%= will_paginate @employees, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </ul>
  </nav>
</div>

<script>
$(document).ready(function() {
  $('[id^=delete-btn]').on('click', function(e) {
    e.preventDefault();

    var employeeId = $(this).attr('id').split('-')[2];

    if (confirm('Tem certeza?')) {
      $.ajax({
        url: '/employees/' + employeeId,
        method: 'DELETE',
        success: function() {
          // Atualiza a página após a exclusão bem-sucedida.
          location.reload(true);
        },
        error: function(error) {
          console.error('Erro ao excluir:', error);
          location.reload(true);
        }
      });
    }
  });
});
</script>

app/views/employees/new.html.erb
<%= render "form", employee: @employee %>

app/views/employees/show.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Meu Colaborador</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-lg-9"> 
      <div class="right_col mt-3" role="main">
        <div class="row">

          <div class="col-md-3">
            <% if @employee&.profile_picture&.attached? %>
              <%= image_tag @employee.profile_picture, class: "img-fluid rounded", style: "max-width: 100%;" %>
            <% else %>
              <%= image_tag "user.png", class: "img-fluid rounded", style: "max-width: 100%;" %>
            <% end %>
          </div>

          <div class="col-md-9">
            <p>
              <strong>Nome:</strong>
              <%= @employee.name %> <%= @employee.lastname %>
            </p>

            <p>
              <strong>Empresa:</strong>
              <%= @employee.companyID %>
            </p>
                  
            <p>
              <strong>Telefone:</strong>
              <%= @employee.phone %>
            </p>
                  
            <p>
              <strong>Cargo:</strong>
              <%= @employee.function %>
            </p>
                  
            <p>
              <strong>Código Pin:</strong>
              <%= @employee.PIN %>
            </p>

            <p>
              <strong>Senha Locker:</strong>
                <% if @employee.pswdSmartlocker.present? %>
                  <%= '*' * @employee.pswdSmartlocker.length %>
                <% else %>
                  N/A
                <% end %>            
            </p>
                  
            <p>
              <strong>ID Card:</strong>
              <% if @employee.cardRFID.present? %>
                <%= '*' * @employee.cardRFID.length %>
              <% else %>
                N/A
              <% end %>
            </p>
                  
            <p>
              <strong>Status:</strong>
              <button class="toggle-status-btn btn <%= @employee.status == 'bloqueado' ? 'btn-danger' : 'btn-primary' %>" data-employee-id="<%= @employee.id %>">
                <i class="lock-icon <%= @employee.status == 'bloqueado' ? 'fa fa-lock' : 'fa fa-unlock' %>"></i>
                <%= @employee.status %>
              </button>
            </p>
            
                  
            <% @employee.workdays.each do |workday| %>
                  
              <p>
                <strong>Dias de trabalho:</strong>
                <% @days_of_week = JSON.parse(workday.dayofweek) rescue [] %>
                <ul>
                  <% @days_of_week.each do |day| %>
                    <li><%= day %></li>
                  <% end %>
                </ul>
              </p>
                    
              <p>
                <strong>Hora de inicio</strong>
                <%= workday.start.strftime("%H:%M") %>
              </p>
                    
                    
              <p>
                <strong>Hora de termino:</strong>
                <%= workday.end.strftime("%H:%M") %>
              </p>
                    
              <p>
                <strong>Trabalha no Feriado</strong>
                <%= workday.holiday ? 'Sim' : 'Não' %>
              </p>
            <% end %>

            <div class="btn-group d-flex align-items-center">
              <%= link_to(edit_employee_path(@employee), class: "btn btn-primary mr-2") do %>
                <i class="fas fa-edit"></i> Editar
              <% end %>
            
              <%= link_to(employees_path, class: "btn btn-secondary mr-2") do %>
                <i class="fas fa-arrow-left"></i> Voltar
              <% end %>
            
              <%= button_to(@employee, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mr-2") do %>
                <i class="fas fa-trash-alt"></i> Excluir
              <% end %>
            
              <button id="reset-pin-btn" class="btn btn-success">
                <i class="fas fa-key"></i> Resetar senha
              </button>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>



<script>
  $(document).ready(function() {
    // Adicione um manipulador de eventos para todos os elementos com a classe "toggle-status-btn"
    $('.toggle-status-btn').on('click', function() {
      var clickedButton = $(this);
      var employeeId = clickedButton.data('employee-id');
      var statusText = $('.status-text[data-employee-id="' + employeeId + '"]');

      $.ajax({
        url: '/employees/' + employeeId + '/toggle_and_save_status',
        method: 'PATCH',
        success: function(data) {
          statusText.text(data.status);

          var lockIcon = clickedButton.find('.lock-icon');
          
          lockIcon.removeClass('fa-lock fa-unlock');
          
          lockIcon.addClass(data.status == 'bloqueado' ? 'fa-lock' : 'fa-unlock');

          clickedButton.removeClass('btn-danger btn-primary');
          clickedButton.addClass(data.status == 'bloqueado' ? 'btn-danger' : 'btn-primary');

          clickedButton.html('<i class="' + lockIcon.attr('class') + '"></i> ' + data.status);
        },
        error: function(error) {
          console.error('Erro ao alternar e salvar o status:', error);
        }
      });
    });
  });
</script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById('reset-pin-btn').addEventListener('click', function() {
      // Chamar a ação AJAX para resetar PIN, enviar SMS e atualizar no banco de dados
      resetPinAndSendSMS('<%= @employee.phone %>');
    });

    function resetPinAndSendSMS(phone) {
      // Adicione lógica AJAX aqui
      $.ajax({
        type: 'PUT',
        url: '<%= reset_pin_employee_path(@employee) %>',
        data: { phone: phone },
        success: function(response) {
          alert(response.message); // Exiba uma mensagem de sucesso
        },
        error: function() {
          alert('Erro ao resetar o PIN e enviar por SMS.');
        }
      });
    }
  });
</script>