config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/inadimplente'
  root 'welcome#index'
  get 'admin', to: 'admin#index'
  get 'dadosuser', to: 'admin#dadosuser'
  get '/manager_users', to: 'manager_users#index', as: 'manager_users_index'
  get 'inadimplente', to: 'static_pages#inadimplente'
  resources :employees
  devise_for :users
  resources :keylockers 

  resources :employees do
    member do
      patch 'toggle_and_save_status'
      put 'reset_pin'
    end
  end

  resources :keylockers do
    member do
      patch 'toggle_and_save_status'
    end
  end

  patch 'manager_users/:id/toggle_finance', to: 'manager_users#toggle_finance', as: :toggle_finance
  patch 'manager_users/:id/toggle_role', to: 'manager_users#toggle_role', as: :toggle_role

  resources :manager_users do
    member do
      delete :destroy
    end
  end

  get '/history_entries', to: 'history_entries#index'

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]

  resources :history_entries, only: [:index, :show, :new, :create, :destroy]


  # config/routes.rb
  resources :user_lockers do
    member do
      post 'assign_keylocker'
      delete 'remove_keylocker/:keylocker_id', to: 'user_lockers#remove_keylocker', as: 'remove_keylocker'
    end
  end

  

  #resources :keylockers, defaults: { format: 'json' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do
    namespace :v1 do
      resources :employees
      get '/employees', to: 'employees#index'
      get '/employees/:employee_id/belongs_to_keylocker/:keylocker_id', to: 'employees#belongs_to_keylocker'
      post '/esp8288params', to: 'employees#esp8288params', via: :post
      post 'check_user', to: 'employees#check_user'
      post 'count_and_track_spaces', to: 'employees#count_and_track_spaces'
      post 'return_key', to: 'employees#return_key'
      post 'key_locker_history', to: 'employees#key_locker_history'
      get '/outro_metodo', to: 'employees#outro_metodo'
      resources :keylockers  # Ajuste para o novo nome do controlador
      #post '/auth/sign_in', to: 'authentication#sign_in'
      devise_for :users, skip: [:registrations], controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    before_create :set_default_status
    has_many :workdays, dependent: :destroy
    belongs_to :user
    has_and_belongs_to_many :keylockers
    has_one_attached :profile_picture
  
    accepts_nested_attributes_for :workdays, reject_if: :all_blank, allow_destroy: true
    validate :at_least_one_keylocker

  
    private

    def at_least_one_keylocker
      errors.add(:base, 'Deve haver pelo menos um locker atribuído') if keylockers.none?
    end
  
    def set_default_status
      self.status ||= 'debloqueado'
    end
  end
  

app/models/history_entry.rb
class HistoryEntry < ApplicationRecord
   
    validates :owner, presence: true
    validates :name_device, presence: true

    scope :unread, -> { where(read: false) }
  end

app/models/keylocker.rb
class Keylocker < ApplicationRecord
    validates_uniqueness_of :owner, scope: [:nameDevice, :ipAddress, :status]
    validates :owner, uniqueness: { scope: [:nameDevice, :ipAddress, :status]}
    has_many :user_lockers
    has_many :users, through: :user_lockers

    has_many :employees_keylockers
    has_and_belongs_to_many :employees

    def toggle_and_save_status!
        # Implemente a lógica para alternar e salvar o status no banco de dados
        self.status = (status == 'bloqueado' ? 'desbloqueado' : 'bloqueado')
        save!
    end
end

app/models/keylog.rb
class Keylog < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
    serialize :result, Hash
end

app/models/user.rb
class User < ApplicationRecord
  before_create :set_default_role
  before_create :set_default_finance
  enum role: { admin: 'admin', user: 'user'}

  has_many :user_lockers
  has_many :keylockers, through: :user_lockers
  has_one :employee #funciona
  has_one :keylocker  # Adicione esta linha
  has_one :address


  #accepts_nested_attributes_for :employees

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_save :ensure_authentication_token

  # Método para atribuir um locker a um usuário
  def assign_keylocker(keylocker)
    self.keylockers << keylocker unless self.keylockers.include?(keylocker)
  end

  # Método para remover um locker de um usuário
  def remove_keylocker(keylocker)
    self.keylockers.delete(keylocker)
  end


  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  private

  def set_default_role
    self.role ||= 'user'
  end

  def set_default_finance
    self.finance ||= 'adimplente'
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.find_by(authentication_token: token)
    end
  end  
end

app/models/user_locker.rb
class UserLocker < ApplicationRecord
  belongs_to :user
  belongs_to :keylocker
end

app/models/workday.rb
class Workday < ApplicationRecord
  belongs_to :employee
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    #before_action :authenticate_admin! # Certifique-se de que apenas administradores têm acesso

    def index
      @employees = Employee.includes(:user).all
      @users = User.all.includes(:keylockers, employee: :keylocker)
    end

    def dadosuser
      @users = [current_user] # Cria um array contendo apenas o usuário atual
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_datetime(datetime_string)
        return unless datetime_string
    
        datetime = Time.parse(datetime_string)
        datetime.strftime('%d/%m/%Y %H:%M:%S')
      rescue ArgumentError
        'Invalid datetime format'
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/historicos_helper.rb
module HistoricosHelper
end

app/helpers/keylockers_helper.rb
module KeylockersHelper
end

app/helpers/manager_users_helper.rb
module ManagerUsersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_lockers_helper.rb
module UserLockersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dadosuser.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Dados do Usuário</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 col-lg-9"> 
            <div class="right_col mt-3" role="main">
                <div class="row">

                    <p>
                        <strong>Perfil de usuário:</strong>
                        <% if current_user.role == 'user' %>
                            <button class="btn btn-primary">
                                <i class="fas fa-user"></i> Usuário
                            </button>
                            <% elsif current_user.role == 'admin' %>
                            <button class="btn btn-success">
                                <i class="fas fa-user-tie"></i> Administrador
                            </button>
                        <% end %>
                    </p>
            
                    <p>
                        <strong>Nome:</strong>
                        <%= current_user.name %> <%= current_user.lastname %>
                    </p>
            
                    <p>
                        <strong>Nome da Empresa:</strong>
                        <%= current_user.nameCompany %> 
                    </p>
            
                    <p>
                        <strong>CNPJ:</strong>
                        <%= current_user.cnpj %>
                    </p>
            
                    <p>
                        <strong>Email:</strong>
                        <%= current_user.email %>
                    </p>
            
                    <p>
                        <strong>Status Financeiro:</strong>
                        <% if current_user.finance == 'adimplente' %>
                            <button class="btn btn-success">
                                <i class="fas fa-check"></i> Adimplente
                            </button>
                            <% elsif current_user.finance == 'inadimplente' %>
                            <button class="btn btn-warning">
                                <i class="fas fa-exclamation-triangle"></i> Inadimplente
                            </button>
                        <% end %>
                    </p>
            
                    <p>
                        <strong>Celular:</strong>
                        <%= current_user.phone %>
                    </p>
            
                    <p>
                        <strong>Código Postal:</strong>
                        <%= current_user.zip_code %>
                    </p>
            
                    <p>
                        <strong>Rua:</strong>
                        <%= current_user.street %>
                    </p>
            
                    <p>
                        <strong>Cidade:</strong>
                        <%= current_user.city %>
                    </p>
            
                    <p>
                        <strong>Estado:</strong>
                        <%= current_user.state %>
                    </p>
            
                    <p>
                        <strong>Bairro:</strong>
                        <%= current_user.neighborhood %>
                    </p>
            
                    <p>
                        <strong>Complemento:</strong>
                        <%= current_user.complement %>
                    </p>
            
                    <p>
                        <strong>Criado em:</strong>
                        <%= current_user.created_at.strftime('%d/%m/%Y - %H:%M:%S') %>
                    </p>
            
                    <p>
                        <strong>Última alteração:</strong>
                        <%= current_user.updated_at.strftime('%d/%m/%Y - %H:%M:%S') %>
                    </p>
                
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/index.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Meus Funcionários Admin</h1>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <% if current_user.admin? %>
                        <p>Você é um administrador.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <%= link_to "New keylocker", new_keylocker_path %>
                        <%= link_to "Atribuir locker", user_lockers_path %>
                        <%= link_to "Ver funconarios", admin_path %>
                        <% else %>
                        <p>Você é um usuário regular.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                            <%= link_to "New employee", new_employee_path %>
                        <% end %>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<p style="color: green"><%= notice %></p>

<% if @employees.present? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 col-lg-9"> 
        <div class="right_col mt-3" role="main">
          <div class="row">
            <% @employees.each do |employee| %>
              <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="card mb-4">
                </br>
                    <div class="text-center">
                        <p>
                            <% if employee.profile_picture.attached? %>
                            <%= image_tag employee.profile_picture, size: '288x288' %>
                            <% else %>
                            <p>Nenhuma imagem disponível</p>
                            <% end %>
                        </p>
                    </div>
                <div class="card-body">
                  <p>
                    <strong>Nome:</strong>
                    <%= employee.name %> <%= employee.lastname %>
                  </p>

                  <p>
                    <strong>Empresa:</strong>
                    <%= employee.companyID %>
                  </p>

                  <p>
                    <strong>Telefone:</strong>
                    <%= employee.phone %>
                  </p>

                  <p>
                    <strong>Cargo:</strong>
                    <%= employee.function %>
                  </p>

                  <p>
                    <strong>Meus Lockers:</strong>
                    <% if employee.keylockers.any? %>
                        <ul>
                        <% employee.keylockers.each do |keylocker| %>
                            <li>
                            <%= keylocker.nameDevice %> - <%= keylocker.status %>
                            </li>
                        <% end %>
                        </ul>
                    <% else %>
                        Nenhum locker associado a esse funcionário.
                    <% end %>
                  </p>

                  <div class="text-center mt-3">
                    <%= link_to employee, class: "btn btn-warning d-inline-block mr-2" do %>
                      <i class="fa fa-search"></i> Exibir
                    <% end %>
                
                    <%= link_to edit_employee_path(employee), class: "btn btn-success d-inline-block mr-2" do %>
                        <i class="fa fa-edit"></i> Editar
                    <% end %>
                
                    <%= button_to employee, method: :delete, class: 'btn btn-danger d-inline-block mt-3', title: 'Excluir', id: "delete-btn-#{employee.id}" do %>
                        <i class="fa fa-trash"></i> Excluir
                    <% end %>                  
                  </div>
                  </br>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div style="text-align: center;">
    <p>Não existe nenhum funcionário</p>
  </div>
<% end %>



<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Controle Funcionários x Lockers</h1>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <% if current_user.admin? %>
                        <p>Você é um administrador.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <%= link_to "New keylocker", new_keylocker_path %>
                        <%= link_to "Atribuir locker", user_lockers_path %>
                        <%= link_to "Ver funconarios", admin_path %>
                        <% else %>
                        <p>Você é um usuário regular.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                            <%= link_to "New employee", new_employee_path %>
                        <% end %>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

Tabela de Employees x Keylockers

<h1>Employees and their Associated Lockers</h1>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
            <th>Employee ID</th>
            <th>Employee Name</th>
            <th>Locker ID</th>
            <th>Locker Name</th>
            </tr>
        </thead>
        <tbody>
            <% @employees.each do |employee| %>
            <% employee.keylockers.each do |keylocker| %>
                <tr>
                <td><%= employee.id %></td>
                <td><%= employee.name %></td>
                <td><%= keylocker.id %></td>
                <td><%= keylocker.nameDevice %></td>
                </tr>
            <% end %>
            <% end %>
        </tbody>
    </table>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartlocker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/public/css/style.css">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>


    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar" class="active">
    <h1><a href="index.html" class="logo">  </a></h1>
        <ul class="list-unstyled components mb-5">
           
            <li class="active">
              <%= link_to root_path do %>
                <span class="fa fa-home"></span> Home
              <% end %>
            </li>
            
            <li class="active">
              <%= link_to keylockers_path do %>
                <span class="fas fa-box"></span> Meus Lockers
              <% end %>
            </li>

            <li class="active">
              <%= link_to user_lockers_path do %>
                <span class="fa fa-user-plus"></span> Atribuir Lockers
              <% end %>
            </li>

            <li class="active">
              <%= link_to manager_users_index_path do %>
                <span class="fa fa-user"></span> Donos de Lockers
              <% end %>
            </li>

            <li class="active">
              <%= link_to employees_path do %>
                <span class="fa fa-user-tie"></span> Meus Colaboradores
              <% end %>
            </li>

            <li class="active">
              <%= link_to history_entries_path do %>
                <span class="fa fa-history"></span> Histórico
              <% end %>
            </li>
        </ul>
        <div class="footer">
            <p>
                Copyright &copy; All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
            </p>
        </div>
    </nav>

    

    <div id="content" class="p-4 p-md-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-primary-orange">
                    <i class="fa fa-bars"></i>
                    <span class="sr-only">Toggle Menu</span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-envelope"></i> Notificação
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Opção 1</a>
                                <a class="dropdown-item" href="#">Opção 2</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Outra Opção</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <% if current_user %>
                              <i class="fa fa-user"></i> <%= current_user.name %>
                            <% else %>

                            <% end %>
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            
                              <%= link_to dadosuser_path, class: 'dropdown-item' do %>
                                <i class="fa fa-fw fa-user"></i>
                                Perfil
                              <% end %> 
      
                              
                              <a class="dropdown-item" href="#">
                                  <i class="fa fa-fw fa-envelope"></i> Inbox
                              </a>
                              
                              <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                                  <i class="fa fa-fw fa-gear"></i>
                                  Settings
                              <% end %> 
      
                              <div class="dropdown-divider"></div>
                              <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                                  <i class="fa fa-fw fa-power-off"></i>                           
                                  Log Out
                              <% end %>  
      
                          </div> 
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <%= yield %>
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="js/main.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartlocker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/applicationOLD.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartlocker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/public/css/style.css">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar" class="active">
        <h1><a href="index.html" class="logo">M.</a></h1>
        <ul class="list-unstyled components mb-5">
           
            <li class="active">
              <%= link_to root_path do %>
                <span class="fa fa-home"></span> Home
              <% end %>
            </li>
            
            <li class="active">
              <%= link_to keylockers_path do %>
                <span class="fas fa-box"></span> Meus Lockers
              <% end %>
            </li>

            <li class="active">
              <%= link_to user_lockers_path do %>
                <span class="fa fa-user-plus"></span> Atribuir Lockers
              <% end %>
            </li>

            <li class="active">
              <%= link_to manager_users_index_path do %>
                <span class="fa fa-user"></span> Donos de Lockers
              <% end %>
            </li>

            <li class="active">
              <%= link_to employees_path do %>
                <span class="fa fa-user-tie"></span> Meus Funcionários
              <% end %>
            </li>

            <li class="active">
              <%= link_to history_entries_path do %>
                <span class="fa fa-history"></span> Histórico
              <% end %>
            </li>
        </ul>
        <div class="footer">
            <p>
                Copyright &copy; All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
            </p>
        </div>
    </nav>

    

    <div id="content" class="p-4 p-md-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-primary-orange">
                    <i class="fa fa-bars"></i>
                    <span class="sr-only">Toggle Menu</span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-envelope"></i> Notificação
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Opção 1</a>
                                <a class="dropdown-item" href="#">Opção 2</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Outra Opção</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user"></i> John Smith </a>
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="#">
                                  <i class="fa fa-fw fa-user"></i> Perfil
                              </a>
      
                              <a class="dropdown-item" href="#">
                                  <i class="fa fa-fw fa-envelope"></i> Inbox
                              </a>
                              
                              <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                                  <i class="fa fa-fw fa-gear"></i>
                                  Settings
                              <% end %> 
      
                              <div class="dropdown-divider"></div>
                              <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                                  <i class="fa fa-fw fa-power-off"></i>                           
                                  Log Out
                              <% end %>  
      
                          </div> 
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <%= yield %>
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="js/main.js"></script>
  </body>
</html>